version: '3'
services:
  devops:
    image: niroopa12/phonpay1-trans:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3

  aws:
    image: niroopa12/phonpay1-recharge:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3


  azure:
    image: niroopa12/phonpay1-dth:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
