version: '3'
services:
  devops:
    image: niroopa12/devops1-repo:latest
    ports:
      - "90:80"
    volumes:
      - "dev-vol"
    deploy:
      replicas: 3

  aws:
    image: niroopa12/aws2-repo:latest
    ports:
      - "91:80"
    volumes:
      - "aws-vol"
    deploy:
      replicas: 3


  azure:
    image: niroopa12/azure3-repo:latest
    ports:
      - "93:80"
    volumes:
      - "azure-vol"
    deploy:
      replicas: 3
