version: '3'
services:
  trans:
    image: niroopa12/phonpay1-trans:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3

  recharge:
    image: niroopa12/phonpay1-recharge:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3


  dth:
    image: niroopa12/phonpay1-dth:latest
    ports:
      - "95:80"
    deploy:
      replicas: 3
